---

- name: Create HANA components list from output JSON
  set_fact:
    components_list: "{{ components_list + [ item.key ] }}"
  loop: "{{ hana_database.components|dict2items }}"

- name: Merge HANA Components list with its depends on components
  set_fact:
    install_comp: "{{  [ item.depends_on ] + components_list }}"
  loop: "{{ components }}"
  when: 'item.component in components_list'

- name: Create unique list of HANA Components
  set_fact:
    hana_components: "{{ install_comp|flatten(levels=1)|unique }}"

# Install HANA Components
- name: Install HANA Components
  include_role:
    name: components-install
    tasks_from: "{{ component }}.yml"
  loop: "{{ hana_components }}"
  loop_control:
    loop_var: component
